# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  heroku_deploy:
    jobs:
      - deploy
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
#      - heroku/deploy-via-git:
#          only-branch: master
      - run: echo $HEROKU_API_KEY
      - run: echo ${HEROKU_API_KEY}
      - run: echo https://heroku:$HEROKU_API_KEY
      - run: echo https://heroku:${HEROKU_API_KEY}
      - run:
          name: git
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
