version: 2.1

jobs:
  build_api_start_up:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
#      - run:
#          command: python server/app.py
#          background: true

  api_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
#      - run: sleep 20
      - run:
          command: python server/app.py
          background: true
      - run: curl http://127.0.0.1:5000/

workflows:
  build_test:
    jobs:
     - build_api_start_up
     - api_test
