version: 2.1

jobs:
  build_api_start_up:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run:
          name: create tmp
          command: |
            mkdir -p /tmp/flask_app
      # 一時ファイルの永続化
      - persist_to_workspace:
          root: /tmp
          paths:
            - flask_app

      - checkout
      - run: mv * /tmp/flask_app
      - run: ls -la /tmp/flask_app
      - run: ls -la /tmp/flask_app/
      - run:
          name: Install Python Dependencies
          command: |
            pwd
            ls
            cd /tmp/flask_app
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            pwd
            ls
      - run: pwd
      - run: ls -la

  api_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run: pwd
      - run: ls -la

      # job間で共有できるスペース
      - attach_workspace:
          at: /tmp/flask_app

      - run: mv /tmp/flask_app/* .
      - run: ls -la
      - run:
          command: |
            python server/app.py
            sleep 10
          background: true
      - run:
          command: |
            curl http://127.0.0.1:5000/
            pytest

workflows:
  build_test:
    jobs:
     - build_api_start_up
     - api_test:
        requires:
          - build_api_start_up
