# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
    build:
        docker:
            - image: alpine
        steps:
            - run:
                name: TEST
                command: |
                  echo $TEST_KEY

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: TEST

