# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  heroku_deploy:
    jobs:
      - deploy
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: pwd test
          command: pwd
      - run:
          name: ls test
          command: ls
      - heroku/install
      - run:
          name: pwd test after install
          command: pwd
      - run:
          name: ls test after install
          command: ls
      - heroku/deploy-via-git:
          only-branch: master
