version: 2.1

jobs:
  build_api_start_up:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run:
          name: create tmp
          command: |
            mkdir -p /tmp/flask_app
      # 一時ファイルの永続化
      - persist_to_workspace:
          root: /tmp
          paths:
            - flask_app

#      - run: cd /tmp/flask_app

      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pwd
            ls
            cd /tmp/flask_app
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
            pwd
            ls
      - run: pwd
      - run: ls -la
#      - run:
#          command: python server/app.py
#          background: true

#      - run: sleep 10
#      - run: curl http://127.0.0.1:5000/
#      - run: pytest

  api_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - run: pwd
      - run: ls -la

      # job間で共有できるスペース
      - attach_workspace:
          at: /tmp/flask_app

      - run:
          command: |
            cd /tmp/flask_app
            pwd
            ls
#      - run: pwd
#      - run: ls -la
#      - run:
#          command: python server/app.py
#          background: true
#      - run: sleep 10
#      - run: curl http://127.0.0.1:5000/
#      - run: pytest

workflows:
  build_test:
    jobs:
     - build_api_start_up
     - api_test:
        requires:
          - build_api_start_up
